flaskapp:
    command: python /app/hello.py
    environment:
        # When env vars are given without a value, they will be passed through
        # from your host environment
        - PGPASSWORD

    volumes:
        - ./app:/app

    ports:
        # HOST : CONTAINER
        - "8877:5000"

